### ISSUE TITLE
Define documentation of how to publish research data in the open

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#10]
Goal: “This is how you make your data public to the rest of the public and beyond”
- [ ] Create a [Data Package](http://specs.frictionlessdata.io/data-packages/)
  - [ ] Create a [JSON Table Schema](http://specs.frictionlessdata.io/json-table-schema/)
- [ ] Validate my Data Package
- [ ] Validate my Data Package's _data_
- [ ] Create DOI and add to `datapackage.json`

**Comment by pwalsh** [comment]
merging into https://github.com/frictionlessdata/pilot-dm4t/issues/20
