### ISSUE TITLE
Get original REFIT SQL database dump

### ISSUE THREAD

**Issue by cblop** [frictionlessdata/pilot-dm4t#14]

**Comment by cblop** [comment]
I have the dump ready to send to you, but be warned: it's 9GB! I'm uploading it to Google Drive now and will send you a link later. Otherwise, do you have a preferred method of transferring large files?

**Comment by cblop** [comment]
I'm also compressing the dump with 7zip, I'll let you know how that goes when it's done.

**Comment by danfowler** [comment]
👍

**Comment by danfowler** [comment]
Google Drive is fine.

**Comment by cblop** [comment]
Here it is: https://drive.google.com/open?id=0B1gP4mtvi6JcWlZSOUZEcDNoS1U

**Comment by danfowler** [comment]
Received 👍
