### ISSUE TITLE
Get original ApatSCHE dump

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#16]

**Comment by pwalsh** [comment]
@danfowler can this be closed?

**Comment by danfowler** [comment]
@cblop do we have this?

**Comment by cblop** [comment]
We don't have the full database dump, and I don't think we can get it from Strathclyde. I think we'll have to work with what we've got.

**Comment by danfowler** [comment]
Good to know.  Closing.
