### ISSUE TITLE
Consider alternative backends for large files

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#22]
- [ ] HDF5 http://www.h5py.org/
- [ ] Feather https://github.com/wesm/feather
- [ ] Blaze http://blaze.readthedocs.io/en/latest/index.html

https://github.com/frictionlessdata/tableschema-py/issues/169

**Comment by pwalsh** [comment]
@danfowler I'd open this on https://github.com/frictionlessdata/tableschema-py rather than here

**Comment by pwalsh** [comment]
Moved to https://github.com/frictionlessdata/implementations/issues/20
