### ISSUE TITLE
How to model !NOTES section

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#4]
[readme](https://pure.strath.ac.uk/portal/files/52873458/REFIT_Readme.txt)

For each column, there are additional notes (!NOTES) about any significant changes that occurred during the study (e.g. `3. Change in signature 24/11/13`) or further detail about what appliances were connected (e.g. `7.Television Site` has the additional notes section: `7.a Television`, `7.b Speakers`, `7.c Telephone`).  Where should this information be stored in the `datapackage.json`?

**Comment by pwalsh** [comment]
@danfowler can this now be closed?

**Comment by danfowler** [comment]
Can go in `description`
