### ISSUE TITLE
How to model type of appliance?

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#5]
Each CSV only has the headers Appliance1...Appliance9.  The type of appliance measured is recorded in the [readme](https://pure.strath.ac.uk/portal/files/52873458/REFIT_Readme.txt).  This is now recorded in the `description` for each column's [schema](http://specs.frictionlessdata.io/json-table-schema/).  Would it be better to store this information the `title` or some other field?

**Comment by pwalsh** [comment]
@danfowler can this now be closed?

**Comment by danfowler** [comment]
Closing `description` is fine
