### ISSUE TITLE
What metadata needs modeling and how?

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#6]
From: https://pure.strath.ac.uk/portal/en/datasets/refit-electrical-load-measurements-cleaned(9ab14b0e-19ac-4279-938f-27f643078cec).html

Specs suggest using `temporal` for "temporal coverage", but this is strictly [optional](http://specs.frictionlessdata.io/data-packages/#optional-fields).

>  Date made available: 16 Jun 2016
>   Publisher University of Strathclyde
>   Temporal coverage Oct 2013 - Jun 2015
>   Date of data production   16 Jun 2016 - 16 Jun 2016
>   Geographical coverage United Kingdom, Loughborough

**Comment by pwalsh** [comment]
@danfowler can this now be closed?

**Comment by danfowler** [comment]
OK, added this field.  Will close when published.

**Comment by pwalsh** [comment]
Can close
