### ISSUE TITLE
Is it necessary, useful to model Units (Watts)

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#7]
Current [specifications](http://specs.frictionlessdata.io/) do not have any allowance for specifying units.  This might be informed by the [deliverable](https://github.com/frictionlessdata/pilot-dm4t/milestone/3).

**Comment by pwalsh** [comment]
@danfowler can this now be closed? Or, what actions can be taken in terms of specs, tooling, and this data?

**Comment by danfowler** [comment]
So, we could go ahead and just add a "units" (or "_units" to flag non-standard) to the fields as an example of Data Package/Table Schema flexibility.  This could provide a start for a bigger discussion on units: https://github.com/frictionlessdata/specs/issues/216

**Comment by pwalsh** [comment]
This is I discussion for a future spec version, but not in scope for current pilot. Closing.
