### ISSUE TITLE
Is it necessary, useful to model constraints?

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-dm4t#8]
Currently, we could model the following constraints:
- [ ] Each appliance can only draw up 4000 watts, so no reading should be higher than this number.

**Comment by pwalsh** [comment]
@danfowler can this now be closed, or? I'd say, yes, absolutely have a constraint for this.

**Comment by danfowler** [comment]
I was coming at this from the perspective of a "dirty" dataset that has already been cleaned to remove these high wattage readings, but, yes, even in the cleaned dataset, especially if it gets updated, it makes sense to model and adds context to the dataset.
